name: auth_repository
description: "A new Flutter package project."
version: 0.1.0
homepage: https://github.com/your_username/auth_repository

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  branding: assets/images/logo.png
  color_dark: "#121212"
  image_dark: assets/images/logo.png
  branding_dark: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#121212"

flutter:
  #use-material-design: true
  #assets:
   # - assets/images/logo.png
  #  - assets/images/logo.png

  # To add custom fonts, uncomment and update the font section accordingly.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
